# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2232143950d8f28dee3778794e31630fde47efe244eb6ff7c81411f69c87b1c11498ba202048e781ff4da00c938e2fb27e2ac944b610851b5a27d0e8d1aaa24b

test:
  secret_key_base: 2d2810548c3ec5e5bf1d3d131f6f08265d1e55e13a8f8bf153304bf38136c1c7ae2ac1c446ca064aa1e0860c860b62722ba6bd13eb5a12fd0df65fedb848306c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
